export const places =
  [
    { "name": "Agra", "description": "A historic city famous for the Taj Mahal." },
    { "name": "Jaipur", "description": "The Pink City known for its rich heritage and palaces." },
    { "name": "Varanasi", "description": "One of the oldest cities, famous for its ghats and temples." },
    { "name": "Delhi", "description": "The capital city of India with a blend of modern and historical sites." },
    { "name": "Mumbai", "description": "The financial capital of India, known for Bollywood and beaches." },
    { "name": "Kolkata", "description": "The City of Joy, rich in culture and colonial architecture." },
    { "name": "Chennai", "description": "A coastal city known for its temples and beaches." },
    { "name": "Hyderabad", "description": "The City of Pearls, famous for its biryani and Charminar." },
    { "name": "Bangalore", "description": "The Silicon Valley of India, known for its pleasant climate." },
    { "name": "Pune", "description": "A cultural and IT hub with a young crowd and historical forts." },
    { "name": "Udaipur", "description": "The City of Lakes, known for its royal palaces." },
    { "name": "Amritsar", "description": "Home to the Golden Temple, a spiritual and historical city." },
    { "name": "Rishikesh", "description": "The Yoga Capital of the World, famous for its ashrams and Ganga Aarti." },
    { "name": "Manali", "description": "A beautiful hill station known for adventure sports and scenic views." },
    { "name": "Shimla", "description": "A colonial-era hill station with a cool climate and scenic beauty." },
    { "name": "Ooty", "description": "A charming hill station in Tamil Nadu with tea gardens and lakes." },
    { "name": "Mysore", "description": "Famous for its palaces, silk, and Dasara festival." },
    { "name": "Jaisalmer", "description": "The Golden City, known for its sand dunes and forts." },
    { "name": "Goa", "description": "A beach paradise known for its nightlife and Portuguese heritage." },
    { "name": "Guwahati", "description": "A gateway to Northeast India, famous for Kamakhya Temple." },
    { "name": "Darjeeling", "description": "Known for its tea gardens and breathtaking views of Kanchenjunga." },
    { "name": "Kochi", "description": "A coastal city in Kerala with a rich colonial past." },
    { "name": "Munnar", "description": "A hill station in Kerala famous for its tea plantations." },
    { "name": "Alleppey", "description": "Known as the Venice of the East, famous for its backwaters." },
    { "name": "Rameswaram", "description": "A spiritual island town with historical temples." },
    { "name": "Kanyakumari", "description": "The southernmost tip of India, where three seas meet." },
    { "name": "Haridwar", "description": "A holy city on the Ganges, famous for the Kumbh Mela." },
    { "name": "Bodh Gaya", "description": "A pilgrimage site where Gautama Buddha attained enlightenment." },
    { "name": "Ajmer", "description": "Home to the famous Ajmer Sharif Dargah." },
    { "name": "Mount Abu", "description": "The only hill station in Rajasthan, known for Dilwara Temples." },
    { "name": "Tawang", "description": "A picturesque town in Arunachal Pradesh with a famous monastery." },
    { "name": "Andaman & Nicobar", "description": "Tropical islands known for beaches, scuba diving, and history." },
    { "name": "Lakshadweep", "description": "A group of coral atolls known for pristine beaches." },
    { "name": "Shillong", "description": "The Scotland of the East, known for its hills and waterfalls." },
    { "name": "Gangtok", "description": "The capital of Sikkim, offering stunning Himalayan views." },
    { "name": "Pondicherry", "description": "A former French colony with beautiful beaches and architecture." },
    { "name": "Mahabalipuram", "description": "A UNESCO site with ancient rock-cut temples." },
    { "name": "Hampi", "description": "A UNESCO World Heritage site with stunning ruins." },
    { "name": "Khajuraho", "description": "Famous for its intricate temple carvings." },
    { "name": "Bikaner", "description": "A desert city in Rajasthan known for its sweets and snacks." },
    { "name": "Srinagar", "description": "The summer capital of J&K, famous for Dal Lake and houseboats." },
    { "name": "Gulmarg", "description": "A ski resort in Kashmir with breathtaking scenery." },
    { "name": "Leh-Ladakh", "description": "A high-altitude desert with monasteries and adventure sports." },
    { "name": "Chandigarh", "description": "A well-planned city designed by Le Corbusier." },
    { "name": "Jodhpur", "description": "The Blue City, known for Mehrangarh Fort and vibrant markets." },
    { "name": "Ranthambore", "description": "A famous national park for tiger spotting." },
    { "name": "Kanha", "description": "A stunning wildlife sanctuary in Madhya Pradesh." },
    { "name": "Kaziranga", "description": "A UNESCO-listed park, home to the one-horned rhinoceros." },
    { "name": "Coorg", "description": "A hill station in Karnataka, famous for coffee plantations." },
    { "name": "Lonavala", "description": "A popular weekend getaway near Mumbai." },
    { "name": "Mahabaleshwar", "description": "Famous for strawberries and scenic viewpoints." },
    { "name": "Alibaug", "description": "A coastal town with beautiful beaches and forts." },
    { "name": "Daman", "description": "A union territory known for its beaches and Portuguese heritage." },
    { "name": "Sundarbans", "description": "A vast mangrove forest, home to the Bengal tiger." },
    { "name": "Kodaikanal", "description": "A misty hill station in Tamil Nadu." },
    { "name": "Chikmagalur", "description": "Famous for coffee plantations and waterfalls." },
    { "name": "Sundarbans", "description": "A UNESCO-listed mangrove forest in West Bengal." },
    { "name": "Konark", "description": "Famous for the Sun Temple, a UNESCO World Heritage site." },
    { "name": "Nashik", "description": "A city known for its vineyards and temples." },
    { "name": "Madurai", "description": "A temple city with the famous Meenakshi Amman Temple." },
    { "name": "Dwarka", "description": "A holy city in Gujarat associated with Lord Krishna." },
    { "name": "Somnath", "description": "A significant Hindu pilgrimage site." },
    { "name": "Sanchi", "description": "A UNESCO site known for its Buddhist stupas." },
    { "name": "Lucknow", "description": "The City of Nawabs, famous for its food and heritage." },
    { "name": "Patna", "description": "The capital of Bihar, rich in history." },
    { "name": "Bhubaneswar", "description": "The Temple City of India, known for ancient temples." },
    { "name": "Raipur", "description": "The capital of Chhattisgarh, growing as an industrial hub." }
  ]
